# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_project.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_logs = QtWidgets.QLabel(self.centralwidget)
        self.label_logs.setGeometry(QtCore.QRect(480, 90, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_logs.setFont(font)
        self.label_logs.setAlignment(QtCore.Qt.AlignCenter)
        self.label_logs.setObjectName("label_logs")
        self.run_test_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_test_button.setEnabled(True)
        self.run_test_button.setGeometry(QtCore.QRect(250, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.run_test_button.setFont(font)
        self.run_test_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.run_test_button.setToolTipDuration(1)
        self.run_test_button.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.run_test_button.setShortcut("")
        self.run_test_button.setObjectName("run_test_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(440, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stop_button.setFont(font)
        self.stop_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stop_button.setToolTipDuration(1)
        self.stop_button.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.stop_button.setShortcut("")
        self.stop_button.setObjectName("stop_button")
        self.logs_button = QtWidgets.QPushButton(self.centralwidget)
        self.logs_button.setGeometry(QtCore.QRect(630, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logs_button.setFont(font)
        self.logs_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logs_button.setToolTipDuration(1)
        self.logs_button.setObjectName("logs_button")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(29, 120, 181, 431))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.treeWidget_select_test = QtWidgets.QTreeWidget(self.frame)
        self.treeWidget_select_test.setGeometry(QtCore.QRect(-10, 0, 191, 391))
        self.treeWidget_select_test.setObjectName("treeWidget_select_test")
        self.treeWidget_select_test.headerItem().setText(0, "1")
        self.select_test_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_test_button.setGeometry(QtCore.QRect(60, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_test_button.setFont(font)
        self.select_test_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.select_test_button.setToolTipDuration(1)
        self.select_test_button.setShortcut("")
        self.select_test_button.setObjectName("select_test_button")
        self.select_all_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_all_button.setGeometry(QtCore.QRect(30, 90, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.select_all_button.setFont(font)
        self.select_all_button.setObjectName("select_all_button")
        self.deselect_all_button = QtWidgets.QPushButton(self.centralwidget)
        self.deselect_all_button.setGeometry(QtCore.QRect(120, 90, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deselect_all_button.setFont(font)
        self.deselect_all_button.setObjectName("deselect_all_button")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(310, 120, 431, 391))
        self.textEdit.setToolTipDuration(1)
        self.textEdit.setObjectName("textEdit")
        self.clear_logs_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_logs_button.setGeometry(QtCore.QRect(660, 520, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clear_logs_button.setFont(font)
        self.clear_logs_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_logs_button.setToolTipDuration(1)
        self.clear_logs_button.setObjectName("clear_logs_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 785, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Run = QtWidgets.QAction(MainWindow)
        self.action_Run.setObjectName("action_Run")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.action_Ctrl_C = QtWidgets.QAction(MainWindow)
        self.action_Ctrl_C.setObjectName("action_Ctrl_C")
        self.action_Stop = QtWidgets.QAction(MainWindow)
        self.action_Stop.setObjectName("action_Stop")
        self.actionCtrl_S = QtWidgets.QAction(MainWindow)
        self.actionCtrl_S.setObjectName("actionCtrl_S")
        self.actionSelect_test = QtWidgets.QAction(MainWindow)
        self.actionSelect_test.setObjectName("actionSelect_test")
        self.actionShow_logs = QtWidgets.QAction(MainWindow)
        self.actionShow_logs.setObjectName("actionShow_logs")
        self.actionClear_logs = QtWidgets.QAction(MainWindow)
        self.actionClear_logs.setObjectName("actionClear_logs")
        self.menuFile.addAction(self.action_Run)
        self.menuFile.addAction(self.action_Stop)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSelect_test)
        self.menuFile.addAction(self.actionShow_logs)
        self.menuFile.addAction(self.actionClear_logs)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_logs.setText(_translate("MainWindow", "Log screen"))
        self.run_test_button.setToolTip(_translate("MainWindow", "Run test"))
        self.run_test_button.setStatusTip(_translate("MainWindow", "Run test"))
        self.run_test_button.setText(_translate("MainWindow", "RUN"))
        self.stop_button.setToolTip(_translate("MainWindow", "Stop run tests"))
        self.stop_button.setStatusTip(_translate("MainWindow", "Stop run"))
        self.stop_button.setText(_translate("MainWindow", "STOP"))
        self.logs_button.setToolTip(_translate("MainWindow", "Show logs"))
        self.logs_button.setStatusTip(_translate("MainWindow", "Show logs"))
        self.logs_button.setText(_translate("MainWindow", "LOGS"))
        self.select_test_button.setToolTip(_translate("MainWindow", "Select folder"))
        self.select_test_button.setStatusTip(_translate("MainWindow", "Select test"))
        self.select_test_button.setText(_translate("MainWindow", "select test"))
        self.select_all_button.setText(_translate("MainWindow", "select all"))
        self.deselect_all_button.setText(_translate("MainWindow", "Remove all"))
        self.clear_logs_button.setToolTip(_translate("MainWindow", "Clear log screen"))
        self.clear_logs_button.setStatusTip(_translate("MainWindow", "Clear log screen"))
        self.clear_logs_button.setText(_translate("MainWindow", "clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.action_Run.setText(_translate("MainWindow", "Run"))
        self.action_Run.setStatusTip(_translate("MainWindow", "Run test"))
        self.action_Run.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_Ctrl_C.setText(_translate("MainWindow", " Ctrl + R"))
        self.action_Stop.setText(_translate("MainWindow", "Stop"))
        self.action_Stop.setStatusTip(_translate("MainWindow", "Stop test"))
        self.action_Stop.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionCtrl_S.setText(_translate("MainWindow", "Ctrl + S"))
        self.actionSelect_test.setText(_translate("MainWindow", "Select test"))
        self.actionSelect_test.setStatusTip(_translate("MainWindow", "Select test"))
        self.actionSelect_test.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionShow_logs.setText(_translate("MainWindow", "Show logs"))
        self.actionShow_logs.setStatusTip(_translate("MainWindow", "Show logs"))
        self.actionShow_logs.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionClear_logs.setText(_translate("MainWindow", "Clear logs"))
        self.actionClear_logs.setStatusTip(_translate("MainWindow", "Clear logs"))
        self.actionClear_logs.setShortcut(_translate("MainWindow", "Ctrl+C"))
